/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a SSHConfigAdaptor -c SSHConfigAdaptor -i SSHConfigHelper.h -l SSHConfigHelper org.presire.sshconfig.xml org.presire.sshconfig.server
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "SSHConfigAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SSHConfigAdaptor
 */

SSHConfigAdaptor::SSHConfigAdaptor(SSHConfigHelper *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SSHConfigAdaptor::~SSHConfigAdaptor()
{
    // destructor
}

int SSHConfigAdaptor::ChangeAuthMode(bool bAuth, QString &strErrMsg)
{
    // handle method call org.presire.sshconfig.server.ChangeAuthMode
    return parent()->ChangeAuthMode(bAuth, strErrMsg);
}

int SSHConfigAdaptor::ExecuteSSHD(const QString &strSSHDComandPath, const QStringList &aryOptions, QString &strStdMsg, QString &strErrMsg)
{
    // handle method call org.presire.sshconfig.server.ExecuteSSHD
    return parent()->ExecuteSSHD(strSSHDComandPath, aryOptions, strStdMsg, strErrMsg);
}

int SSHConfigAdaptor::ReadSSHFile(const QString &strFilePath, QString &strContents, QString &strErrMsg)
{
    // handle method call org.presire.sshconfig.server.ReadSSHFile
    return parent()->ReadSSHFile(strFilePath, strContents, strErrMsg);
}

int SSHConfigAdaptor::WriteSSHFile(const QString &strSrcSSHFile, const QString &strBakSSHFile, const QString &strTmpSSHFile, QString &strErrMsg)
{
    // handle method call org.presire.sshconfig.server.WriteSSHFile
    return parent()->WriteSSHFile(strSrcSSHFile, strBakSSHFile, strTmpSSHFile, strErrMsg);
}

